version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: ["celery", "-A", "bitly", "worker", "-l", "info"]
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "16379:6379"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 

volumes:
  postgres_data:
