# Generated by Django 5.1.3 on 2024-11-27 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_link', models.URLField(max_length=500, verbose_name='Исходная ссылка')),
                ('short_link', models.CharField(max_length=100, unique=True, verbose_name='Короткая ссылка')),
                ('redirects_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во переходов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'links',
            },
        ),
    ]
