# Generated by Django 5.1.3 on 2024-12-04 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='awards', verbose_name='Иконка')),
                ('redirects_count', models.PositiveIntegerField(verbose_name='Кол-во переходов для награды')),
            ],
            options={
                'db_table': 'awards',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_link', models.URLField(max_length=500, verbose_name='Исходная ссылка')),
                ('short_link', models.CharField(max_length=100, unique=True, verbose_name='Короткая ссылка')),
                ('redirects_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во переходов')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='links', to='links.tag', verbose_name='Теги')),
            ],
            options={
                'db_table': 'links',
                'ordering': ['-redirects_count'],
            },
        ),
        migrations.CreateModel(
            name='LinkAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_assignment', models.DateField(auto_now_add=True, verbose_name='Дата присвоения')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.award')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.link')),
            ],
            options={
                'db_table': 'links_awards',
                'unique_together': {('award', 'link')},
            },
        ),
        migrations.AddField(
            model_name='award',
            name='link',
            field=models.ManyToManyField(related_name='awards', through='links.LinkAward', to='links.link'),
        ),
    ]
