# Generated by Django 5.1.3 on 2024-11-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='links', to='links.tag', verbose_name='Теги'),
        ),
    ]
