# Generated by Django 5.1.3 on 2024-11-30 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_link_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='', verbose_name='Иконка')),
            ],
            options={
                'db_table': 'awards',
            },
        ),
        migrations.CreateModel(
            name='UserAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_assignment', models.DateField(auto_now_add=True, verbose_name='Дата присвоения')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.award')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'award')},
            },
        ),
        migrations.AddField(
            model_name='award',
            name='user',
            field=models.ManyToManyField(related_name='awards', through='links.UserAward', to=settings.AUTH_USER_MODEL),
        ),
    ]
