# Generated by Django 5.1.3 on 2024-11-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_award_useraward_award_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='redirects_count',
            field=models.PositiveIntegerField(default=100, verbose_name='Кол-во переходов для награды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='icon',
            field=models.ImageField(upload_to='awards', verbose_name='Иконка'),
        ),
    ]
