# Generated by Django 5.1.3 on 2024-12-01 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_alter_useraward_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-redirects_count']},
        ),
        migrations.CreateModel(
            name='LinkAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_assignment', models.DateField(auto_now_add=True, verbose_name='Дата присвоения')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.award')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.link')),
            ],
            options={
                'db_table': 'links_awards',
                'unique_together': {('award', 'link')},
            },
        ),
        migrations.AddField(
            model_name='award',
            name='link',
            field=models.ManyToManyField(related_name='awards', through='links.LinkAward', to='links.link'),
        ),
        migrations.DeleteModel(
            name='UserAward',
        ),
    ]
